export const CHANGE_LEFT_TOP = "CHANGE_LEFT_TOP";
export const CHANGE_LEFT_DOWN = "CHANGE_LEFT_DOWN";
export const CHANGE_RIGHT_TOP = "CHANGE_RIGHT_TOP";
export const CHANGE_RIGHT_DOWN = "CHANGE_RIGHT_DOWN";
